name: Renovate Dependencies from Hardening Manifest

on:
  workflow_dispatch:
  schedule:
    - cron: '6 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: x64
    
    - name: Install niet for yaml parsing
      run: pip install -U niet

    - name: Parse urls, sub arm and download files from hardening manifest
      run: |-
        OIFS="$IFS"
        IFS="|"
        for i in $(IFS="|" niet resources hardening_manifest.yaml -f ifs); do
            URL=$(echo ${i} | niet url)
            FILE=$(echo ${i} | niet filename)
            echo $URL
            wget $URL -O $FILE
        done
        IFS="${OIFS}"

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Renovate Dependencies: ${timestamp}" || exit 0
        git push
